# Generated by Django 3.1.7 on 2021-03-17 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_letter_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='letter_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
